apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-ui-pod
  template:
    metadata:
      labels:
        app: web-ui-pod
    spec:
      serviceAccountName: web-ui-account
      containers:
      - name: web-ui-container
        image: gcr.io/phading-prod/web-ui:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
spec:
  selector:
    app: web-ui-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: web-ui-lb-health-check
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: web-ui
