apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-ui-pod
  template:
    metadata:
      labels:
        app: web-ui-pod
    spec:
      serviceAccountName: web-ui-account
      containers:
      - name: web-ui-container
        image: gcr.io/phading-prod/web-ui:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: web-ui-neg-health-check
spec:
  healthCheck:
    port: 8080
    type: HTTP
    requestPath: /healthz
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
spec:
  selector:
    app: web-ui-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: web-ui-lb-health-check
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: web-ui
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web-ui-route-external
spec:
  parentRefs:
  - name: phading-gateway-external
    sectionName: https
  hostnames:
  - www.secount.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: web-ui
      port: 8080
