export let NATURAL_NAME_LENGTH_LIMIT = 100;
export let USERNAME_LENGTH_LIMIT = 100;
export let PASSWORD_LENGTH_LIMIT = 100;
export let CONTACT_EMAIL_LENGTH_LIMIT = 100;
export let DESCRIPTION_LENGTH_LIMIT = 1000;
